server:
 port: 8888
spring:
 datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: 111
  url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Hongkong
mybatis:
 configuration:
  map-underscore-to-camel-case: true
mapper:
 identity: MYSQL
logging:
 level:
  com.yc.springcloud812: debug
